server:
  port: 8081
  servlet:
    context-path: /api/v1
spring:
  application:
    name: RomStation
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_hyper
    username: postgres
    password: Admin@123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
